package MusicApp;


/**
* MusicApp/MusicProfile.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hello.idl
* 25. september 2014 kl 14.31 CEST
*/

public interface MusicProfile extends MusicProfileOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface MusicProfile
