package MusicApp;

/**
* MusicApp/MusicProfileHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hello.idl
* 25. september 2014 kl 14.31 CEST
*/

public final class MusicProfileHolder implements org.omg.CORBA.portable.Streamable
{
  public MusicApp.MusicProfile value = null;

  public MusicProfileHolder ()
  {
  }

  public MusicProfileHolder (MusicApp.MusicProfile initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MusicApp.MusicProfileHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MusicApp.MusicProfileHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MusicApp.MusicProfileHelper.type ();
  }

}
