package MusicApp;


/**
* MusicApp/MusicProfileOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hello.idl
* 25. september 2014 kl 14.31 CEST
*/

public interface MusicProfileOperations 
{
  int getTimesPlayed (String song_id);
  int getTimesPlayedByUser (String user_id, String song_id);
  int getUserProfile (String user_id, String song_id, MusicApp.UserHolder user);
} // interface MusicProfileOperations
