package MusicApp;

import java.util.ArrayList;
import java.util.List;


/**
* MusicApp/User.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hello.idl
* 25. september 2014 kl 14.31 CEST
*/

public abstract class User implements org.omg.CORBA.portable.StreamableValue
{
  public String id = null;
  public List<Song> songs = null;
  public int total_play_count=0;
  
  private static String[] _truncatable_ids = {
    MusicApp.UserHelper.id ()
   
  };

  public String[] _truncatable_ids() {
    return _truncatable_ids;
    
  }

  public void _read (org.omg.CORBA.portable.InputStream istream)
  {
    this.id = istream.read_string ();
    int _len0 = istream.read_long ();
    this.songs = new ArrayList<Song>();
    for (int _o1 = 0;_o1 < _len0; ++_o1)
      this.songs.add( MusicApp.SongHelper.read (istream));
    this.total_play_count = istream.read_long();
  }

  public void _write (org.omg.CORBA.portable.OutputStream ostream)
  {
    ostream.write_string (this.id);
    ostream.write_long (this.songs.size());
    for (int _i0 = 0;_i0 < this.songs.size(); ++_i0)
      MusicApp.SongHelper.write (ostream, this.songs.get(_i0));
    ostream.write_long(this.total_play_count);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MusicApp.UserHelper.type ();
  }
} // class User
